postgresql-ha:
  postgresqlImage:
    tag: "10"
    # tag: 11
  pgpoolImage:
    tag: "4"
  global:
    postgresql:
      username: postgres
      password: password
      database: awx
  postgresql:
    replicaCount: 2
  pgpool:
    useLoadBalancing: false
  service:
    type: ClusterIP
