# code: language=ansible insertSpaces=true tabSize=2

# AWX - Operator management
# Manages AWX operator on K8S


- hosts: awx_cluster
  tasks:

    # --- Common ---

    - name: Assertion
      assert:
        that:
          - awx_mode | default('') in ['migration', 'managed']
        fail_msg: "Variable 'awx_mode' must be 'migration' or 'managed', not '{{ awx_mode | default('empty') }}'"
      tags: [always]

    - name: Set facts
      set_fact:
        _operator_yaml: "../files/awx-operator-{{ awx_operator_version }}.yml"
        _awx_yaml: "../templates/awx-{{ awx_mode }}.yml.j2"
      tags: [always]

    # --- Deployment and removal ---

    - name: Apply AWX operator
      k8s:
        definition: "{{ lookup('file', _operator_yaml) }}"
        namespace: default
        state: present
      tags: [never, apply-operator]

    - name: Apply AWX resources
      k8s:
        definition: "{{ lookup('template', _awx_yaml) }}"
        namespace: "{{ kubernetes_namespace }}"
        state: present
      tags: [never, apply]

    - name: Delete AWX resources
      k8s:
        definition: "{{ lookup('template', _awx_yaml) }}"
        namespace: "{{ kubernetes_namespace }}"
        state: absent
      tags: [never, delete]

    - name: Delete AWX operator
      k8s:
        definition: "{{ lookup('file', _operator_yaml) }}"
        namespace: default
        state: absent
      tags: [never, delete-operator]
